// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetPropertyGuardsByContentTypeAliasData, GetPropertyGuardsByContentTypeAliasErrors, GetPropertyGuardsByContentTypeAliasesData, GetPropertyGuardsByContentTypeAliasesErrors, GetPropertyGuardsByContentTypeAliasesResponses, GetPropertyGuardsByContentTypeAliasResponses, GetPropertyGuardsData, GetPropertyGuardsErrors, GetPropertyGuardsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class PropertyGuardService {
    public static getPropertyGuards<ThrowOnError extends boolean = false>(options?: Options<GetPropertyGuardsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetPropertyGuardsResponses, GetPropertyGuardsErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/propertyguard/api/v1/GetPropertyGuards',
            ...options
        });
    }
    
    public static getPropertyGuardsByContentTypeAlias<ThrowOnError extends boolean = false>(options?: Options<GetPropertyGuardsByContentTypeAliasData, ThrowOnError>) {
        return (options?.client ?? client).get<GetPropertyGuardsByContentTypeAliasResponses, GetPropertyGuardsByContentTypeAliasErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/propertyguard/api/v1/GetPropertyGuardsByContentTypeAlias',
            ...options
        });
    }
    
    public static getPropertyGuardsByContentTypeAliases<ThrowOnError extends boolean = false>(options?: Options<GetPropertyGuardsByContentTypeAliasesData, ThrowOnError>) {
        return (options?.client ?? client).get<GetPropertyGuardsByContentTypeAliasesResponses, GetPropertyGuardsByContentTypeAliasesErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/propertyguard/api/v1/GetPropertyGuardsByContentTypeAliases',
            ...options
        });
    }
}
