// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44303' | (string & {});
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown | string | null | string | null | number | null | string | null | string | null | undefined;
};

export type PropertyGuardDto = {
    documentTypeAlias: string;
    propertyAlias: string;
    documentTypeUnique?: string | null;
    propertyTypeUnique?: string | null;
    documentTypeName?: string | null;
    propertyTypeName?: string | null;
    icon?: string | null;
    featureKey: string;
    message: string;
    permissions: Array<string>;
    source: PropertyGuardSource;
};

export type PropertyGuardSource = 'Code' | 'Config' | 'Ui';

export type GetPropertyGuardsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/propertyguard/api/v1/GetPropertyGuards';
};

export type GetPropertyGuardsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetPropertyGuardsError = GetPropertyGuardsErrors[keyof GetPropertyGuardsErrors];

export type GetPropertyGuardsResponses = {
    /**
     * OK
     */
    200: Array<PropertyGuardDto>;
};

export type GetPropertyGuardsResponse = GetPropertyGuardsResponses[keyof GetPropertyGuardsResponses];

export type GetPropertyGuardsByDocumentTypeAliasData = {
    body?: never;
    path?: never;
    query?: {
        documentTypeAlias?: string;
    };
    url: '/umbraco/propertyguard/api/v1/GetPropertyGuardsByDocumentTypeAlias';
};

export type GetPropertyGuardsByDocumentTypeAliasErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetPropertyGuardsByDocumentTypeAliasError = GetPropertyGuardsByDocumentTypeAliasErrors[keyof GetPropertyGuardsByDocumentTypeAliasErrors];

export type GetPropertyGuardsByDocumentTypeAliasResponses = {
    /**
     * OK
     */
    200: Array<PropertyGuardDto>;
};

export type GetPropertyGuardsByDocumentTypeAliasResponse = GetPropertyGuardsByDocumentTypeAliasResponses[keyof GetPropertyGuardsByDocumentTypeAliasResponses];

export type GetPropertyGuardsByDocumentTypeAliasesData = {
    body?: never;
    path?: never;
    query?: {
        documentTypeAliases?: Array<string>;
    };
    url: '/umbraco/propertyguard/api/v1/GetPropertyGuardsByDocumentTypeAliases';
};

export type GetPropertyGuardsByDocumentTypeAliasesErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetPropertyGuardsByDocumentTypeAliasesError = GetPropertyGuardsByDocumentTypeAliasesErrors[keyof GetPropertyGuardsByDocumentTypeAliasesErrors];

export type GetPropertyGuardsByDocumentTypeAliasesResponses = {
    /**
     * OK
     */
    200: Array<PropertyGuardDto>;
};

export type GetPropertyGuardsByDocumentTypeAliasesResponse = GetPropertyGuardsByDocumentTypeAliasesResponses[keyof GetPropertyGuardsByDocumentTypeAliasesResponses];
