// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44303' | (string & {});
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown | string | null | string | null | number | null | string | null | string | null | undefined;
};

export type PropertyGuardDto = {
    contentTypeAlias: string;
    propertyAlias: string;
    featureKey: string;
    message: string;
};

export type GetPropertyGuardsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/propertyguard/api/v1/GetPropertyGuards';
};

export type GetPropertyGuardsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetPropertyGuardsError = GetPropertyGuardsErrors[keyof GetPropertyGuardsErrors];

export type GetPropertyGuardsResponses = {
    /**
     * OK
     */
    200: Array<PropertyGuardDto>;
};

export type GetPropertyGuardsResponse = GetPropertyGuardsResponses[keyof GetPropertyGuardsResponses];

export type GetPropertyGuardsByContentTypeAliasData = {
    body?: never;
    path?: never;
    query?: {
        contentTypeAlias?: string;
    };
    url: '/umbraco/propertyguard/api/v1/GetPropertyGuardsByContentTypeAlias';
};

export type GetPropertyGuardsByContentTypeAliasErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetPropertyGuardsByContentTypeAliasError = GetPropertyGuardsByContentTypeAliasErrors[keyof GetPropertyGuardsByContentTypeAliasErrors];

export type GetPropertyGuardsByContentTypeAliasResponses = {
    /**
     * OK
     */
    200: Array<PropertyGuardDto>;
};

export type GetPropertyGuardsByContentTypeAliasResponse = GetPropertyGuardsByContentTypeAliasResponses[keyof GetPropertyGuardsByContentTypeAliasResponses];

export type GetPropertyGuardsByContentTypeAliasesData = {
    body?: never;
    path?: never;
    query?: {
        contentTypeAliases?: Array<string>;
    };
    url: '/umbraco/propertyguard/api/v1/GetPropertyGuardsByContentTypeAliases';
};

export type GetPropertyGuardsByContentTypeAliasesErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetPropertyGuardsByContentTypeAliasesError = GetPropertyGuardsByContentTypeAliasesErrors[keyof GetPropertyGuardsByContentTypeAliasesErrors];

export type GetPropertyGuardsByContentTypeAliasesResponses = {
    /**
     * OK
     */
    200: Array<PropertyGuardDto>;
};

export type GetPropertyGuardsByContentTypeAliasesResponse = GetPropertyGuardsByContentTypeAliasesResponses[keyof GetPropertyGuardsByContentTypeAliasesResponses];
